### ISSUE TITLE
Instructor Checklist

### ISSUE THREAD

**Issue by itcarroll** [edf-org/2020-08-17-edf-online#2]
## Before the workshop, instructors will

- [x] Decide on the order of the lessons and who will teach what modules
- [x] Set up the workshop website using the workshop template and send to The Carpentries Workshop Administration Team. Detailed instructions are in this repo’s README.
- [x] Create a collaborative document for the workshop (e.g. an Etherpad)
- [x] Assist the host in recruiting helpers if possible
- [ ] Assist the host in ensuring the workshop location is accessible
- [ ] Share emergency contact information with host in case of last minute changes
- [ ] Practice teaching the material
- [x] Remind the host of the necessary equipment
- [ ] Join a community discussion
- [x] Confirm criteria for reimbursement (per diem or save receipts)

## During the workshop instructors will

- [ ] Review Code of Conduct with learners
- [ ] Remind learners to use sticky notes to give feedback
- [ ] Get feedback at lunch and end of each day using minute cards
- [x] Support host in collecting attendee names and emails
- [ ] Send out the post-workshop survey at the very end of the workshop

## After the workshop instructors will

- [ ] Remind the host to send workshop attendance data to The Carpentries Workshop Administration Team
- [x] Submit receipts for reimbursement
- [ ] Send their own feedback to the Workshop Administration Team including any configuration problems
- [ ] Take part in a community discussion
- [ ] Report any lesson errors or suggest improvements on GitHub or by email to The Carpentries Workshop Administration Team
